# Metadata
id: "004"
title: OpenAPI Specification for REST APIs
status: active
created: 2025-10-08
updated: 2025-10-08

# Human Documentation
context: |
  REST API components have inconsistent or missing API documentation, making integration difficult and error-prone.

decision: |
  All components exposing REST APIs must provide a complete OpenAPI 3.x specification at docs/reference/openapi.yaml.

rationale: |
  OpenAPI is the industry standard for REST API documentation, enables automatic client generation, interactive testing, and contract validation.

consequences: |
  Developers must maintain OpenAPI specs alongside code. Non-REST components (CLIs, libraries) are exempt from this requirement.

examples:
  compliant: |
    # docs/reference/openapi.yaml
    openapi: 3.0.0
    info:
      title: My API
      version: 1.0.0
    paths:
      /users:
        get:
          summary: List users
          responses:
            '200':
              description: Success
              content:
                application/json:
                  schema:
                    type: array
                    items:
                      type: object

  violation: |
    # docs/api.md (markdown instead of OpenAPI)

    ## GET /users
    Returns list of users

    # Or missing OpenAPI file entirely for REST API component

# Machine-Readable Constraints
constraints:
  allowed:
    - openapi-3.0
    - openapi-3.1

  forbidden:
    - swagger-2.0
    - markdown-api-docs
    - postman-collections

  patterns:
    - regex: "^openapi:\\s*3\\.[0-1]\\."
      description: Must use OpenAPI 3.x specification
    - regex: "^paths:"
      description: Must define API paths
    - regex: "responses:"
      description: Must define responses for each endpoint

  thresholds:
    min_endpoints_documented: 1
    openapi_version_min: "3.0.0"

# Validation Configuration
validation:
  levels:
    - static-analysis
    - unit
    - integration

  enforcement_method: linter

  test_patterns:
    - "tests/unit/openapi/*.test.js"
    - "tests/integration/api-contract/*.test.js"

  tools:
    - name: swagger-cli
      config: null
    - name: openapi-validator
      config: .validation/openapi-rules.json
    - name: spectral
      config: .spectral.yaml
